### PR TITLE
fix (core): register host when component is requested

### LINKED ISSUE #31: Remove initialize step from client
Have an `isReady` state on client and set an EventEmitter once the server responded with host id,
in the meantime keep all components render in a queue and once the event has been triggered - render.

this will simplify the api of creating a Dynamico client

### PR DESCRIPTION
**Pull request by eladav**
* no need to manually call initialize
* code requests are queued and wait for when the host is registered

fixes #31

### CODE REVIEW

File: client/core/lib/Client.ts [hunk 1]
```diff
@@ -41,6 +41,12 @@ interface RegisterHostResponse {
   issues: Issues;
 }
 
+enum ReadyState {
```
Comment (EladBezalel) [inline client/core/lib/Client.ts]: const enum
