### PR TITLE
fix (core): skip save when get component requests response is not ok

### LINKED ISSUE #32: Dynamico client saves error as a component
if server fails to respond with host id and a component still tries to render we get an err from the server which then is saved to localStorage

### PR DESCRIPTION
**Pull request by eladav**
* followed the Fetch API and used the `response.ok` property that is set to false when the status code is bigger than 299
* added custom error which is thrown along with the response object and the response text
* added tests
fixes #32

### CODE REVIEW

File: client/core/lib/Client.ts [hunk 1]
```diff
@@ -134,11 +134,14 @@ export class DynamicoClient {
...
     });
 
-    const { statusCode, version, code } = await this.fetcher(url).then(async (res: Response) => ({
-      statusCode: res.status,
-      version: res.headers.get('dynamico-component-version') as string,
-      code: await res.text()
-    }));
+    const { statusCode, version, code } = await this.fetcher(url).then(async (res: Response) => {
+      if (!res.ok) throw new ComponentGetFailedError(res.statusText, res);
+      return {
```
Comment (EladBezalel) [inline client/core/lib/Client.ts]: can we have a linebreak here? :D
